const ERROR_CODE = {
  SUCCESS_CREATE: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED_ERROR: 401,
  FORBIDDEN_ERROR: 403,
  NOT_FOUND: 404,
  CONFLICT_ERROR: 409,
  INTERNAL_SERVER_ERROR: 500,
};

module.exports = { ERROR_CODE };
